### ISSUE TITLE
Select mocking framework

### ISSUE THREAD

**Issue by paneq** [perplexes/m2r#13]
I don't want to write tests like that: https://github.com/paneq/m2r/blob/connection-refactoring/test/handler_test.rb#L79. `shoulda` was mentiond in `helper.rb` but we removed it because it was not used. Would that be ok to use it?

**Comment by mostlyobvious** [comment]
Mocha is fairly good. Shoulda wasnt for mocking AFAIK.

**Comment by paneq** [comment]
Doh, obviously I was thinking about `mocha`. Not the most fresh brain at 3 a.m. :)
