### ISSUE TITLE
Connection informed of url scheme used

### ISSUE THREAD

**Issue by mostlyobvious** [perplexes/m2r#16]
Is it possible to retrieve wheter mongrel2 serves particular connection with SSL?

**Comment by paneq** [comment]
https://github.com/rfk/m2wsgi/blob/master/m2wsgi/io/base.py#L980

**Comment by mostlyobvious** [comment]
Seems to be default in most of adapters: https://github.com/rack/rack/blob/master/lib/rack/handler/webrick.rb#L48

**Comment by paneq** [comment]
https://github.com/zedshaw/mongrel2/issues/140

**Comment by paneq** [comment]
I would rather guess based on this `ENV` if present and based on port otherwise. Sorry for those who use `443` to serve pure HTTP :)

**Comment by paneq** [comment]
This was fixed in m2 and we can start working on it.

**Comment by paneq** [comment]
I wanted to check it in `1.8.0` relased but: https://github.com/zedshaw/mongrel2/issues/145
