### ISSUE TITLE
Use newest api from ffi-rzmq

### ISSUE THREAD

**Issue by paneq** [perplexes/m2r#23]
```
Breaking API Change from 0.9.3 to 0.9.5

The 0mq library functions zmq_send() and zmq_recv()
were changed to zmq_sendmsg() and zmq_recvmsg(
with the 0mq 3.x API change. I have changed the bindin
to always use #sendmsg and #recvmsg. This breaks
existing code. This should be the last breaking change
heading into the 1.0 release of these bindings.
```

https://github.com/chuckremes/ffi-rzmq/issues/56

**Comment by mostlyobvious** [comment]
Libraries should have lesser restrictions on gem versions. We can implement strategies for different `ffi-rzmq` APIs.

**Comment by perplexes** [comment]
Can we detect which version of a particular gem is loaded at runtime?

**Comment by mostlyobvious** [comment]
@perplexes most of gems follows this policy: `ruby -rffi-rzmq/version -e 'puts ZMQ::VERSION'`

**Comment by paneq** [comment]
We do not use `sendmsg` and `recvmsg` methods from the binding itself. We relay on `recv_string` and `send_string` which were not changed between versions.
