### ISSUE TITLE
Downcase/upcase of utf8 headers

### ISSUE THREAD

**Issue by paneq** [perplexes/m2r#24]
Do we care about such headers ? 

```
irb(main):001:0> "żółć".upcase
=> "żółć"
```

Shall we use library like http://unicode-utils.rubyforge.org/ for such purpose ?

**Comment by mostlyobvious** [comment]
I don't know of any mongrel headers in utf8 but in general: http://tools.ietf.org/html/rfc2616#section-2.2

In my opinion no.

**Comment by paneq** [comment]
Not mongrel, but maybe some users send `X-Żółć` :) I agree with `RFC` argument.
