### ISSUE TITLE
Install mongrel2 on CI

### ISSUE THREAD

**Issue by mostlyobvious** [perplexes/m2r#39]
This is related to #36.

**Comment by paneq** [comment]
@pawelpacana How is it going ?

**Comment by mostlyobvious** [comment]
Done, both 1.7.5 and 1.8 are installed before tests run. They are in /opt/mongrel2-1.7.5 and /opt/mongrel2-1.8.0 respectively.

**Comment by paneq** [comment]
![So much win](http://images2.wikia.nocookie.net/__cb20120101114933/nonsensopedia/images/thumb/3/31/So-much-win.png/430px-So-much-win.png)
